Module5 task1
htmlacademy-nodejs/22908-keksobooking pull request #10
Opened 2018-10-14 11:59 UTC by RayProud

2018-10-14 12:06 UTC, RayProud commented on src/commands/server.js
> +    return app;
Это нормально, что я отсюда верну приложение?
Я просто не придумал, как иначе можно было бы сервер использовать в тестах.

2018-10-14 12:06 UTC, RayProud commented on test/server.test.js
> +        assert.deepEqual(total, offersLength);
Я правильно понимаю, что количество элементов в `data` должно быть равно `total`?
В ТЗ про это ни слова. Как и в задании.

2018-10-14 12:06 UTC, RayProud commented on test/server.test.js
> +        assert.deepEqual(limit, 20);
`total` и `offers.length` должны быть меньше `limit`?

2018-10-14 12:06 UTC, RayProud commented on test/server.test.js
> +  it(`?skip=5 responds with different skip`, () => {
Как лучше оформлять тесты на GET-параметры? В этом же `describe `,  как я здесь сделал или в отдельный выносить?

И нужно ли внутри него проверять то, что пришел json, что в нем есть другие поля или это должны гарантировать предыдущие тесты?

2018-10-14 12:07 UTC, RayProud commented
Начал писать тесты и понял, что в задании и в ТЗ есть не до конца ясные вещи, поэтому решил сперва задать несколько вопросов.

2018-10-14 14:28 UTC, TheDarkestDay commented on src/commands/server.js
> +    return app;
Да, так и делается.

2018-10-14 14:44 UTC, TheDarkestDay requested changes

2018-10-14 14:44 UTC, TheDarkestDay commented on test/server.test.js
> +        assert.deepEqual(limit, 20);
`total` - общее число записей в базе.
`skip` - кол-во "пропущенных" элементов с начала списка (другими словами - индекса начала подмассива, который нас на самом деле интересует). По-умолчанию равен 0
`limit` - максимальное кол-во элементов в выдаче.

Например, для массива из 5 элементов при параметрах skip, limit равных 1, 3 мы получим массив из элементов стоящих на позициях 1,2,3 (нулевой пропустили, а последний не поместился).

Надеюсь, теперь все прояснилось.

2018-10-14 14:44 UTC, TheDarkestDay commented on test/server.test.js
> +  it(`?skip=5 responds with different skip`, () => {
Предлагаю оставить как есть сейчас, выглядит уместно.

2018-10-14 14:44 UTC, TheDarkestDay commented on test/server.test.js
> +  it(`?skip=5 responds with different skip`, () => {
Предложенные тесты лучше реализовать отдельно, здесь их дублировать не нужно.

2018-10-14 17:32 UTC, RayProud commented on test/server.test.js
> +  it(`?skip=5 responds with different skip`, () => {
Понял. Спасибо.

2018-10-14 17:33 UTC, RayProud commented on test/server.test.js
> +        assert.deepEqual(limit, 20);
Да, теперь ясно.

2018-10-15 18:24 UTC, RayProud reviewed
Тут еще несколько моментов появилось, к которым у меня вопросы.

2018-10-15 18:24 UTC, RayProud commented on src/commands/main.js
> +      const entities = Array.from({length: entitiesCount}, () => generateEntity(entity));
С `fill` была ошибка — generateEntity не вызывался каждый раз, а только единожды и заполнял массив одним и тем же элементом.

2018-10-15 18:24 UTC, RayProud commented on src/commands/server.js
> +  if (err) {
Это вынесу в отдульную функцию и в папку к серверу.
Пока хочу понять, нормально ли это выглядит?

2018-10-15 18:24 UTC, RayProud commented on src/commands/server.js
> +        const currentErrMsg = `${cur.fieldName} ${cur.errorMessage}`;
Если формат html, то нормально же будет просто перечислить все ошибки?

2018-10-15 18:24 UTC, RayProud commented on src/commands/server/errors/validation-error.js
> +    this.errors = errors;
Судя по коду лектора, это пригодится далее, для валидации post-запроса.

2018-10-15 18:24 UTC, RayProud commented on src/commands/server/routes/offers-router.js
> +    throw new IllegalArgumentError(`date should be number`);
Хотя вот тут мне неочевидно. Это должна быть ошибка Bad Request или Validation Error?

2018-10-15 18:24 UTC, RayProud commented on test/server.test.js
> +  it(`with real date responds with an object with the same date which was in the request`, async () => {
Не могу понять, почему при запуске mocha тесты так и весят? То есть, запустил, а дальше команды вводить нельзя. Только после `ctrl + c`.

2018-10-16 10:56 UTC, TheDarkestDay requested changes

2018-10-16 10:56 UTC, TheDarkestDay commented on src/commands/main.js
> +      const entities = Array.from({length: entitiesCount}, () => generateEntity(entity));
Можно вот так сделать: `[...new Array(entitiesCount)].map(generateEntity)`

2018-10-16 10:56 UTC, TheDarkestDay commented on src/commands/server.js
> +  if (err) {
Выглядит так, что хочется разнести код генерации ошибки для разных представлений (если я все верно понял, ты в одном случае отдаешь просто текст, а в другом - JSON) в разные функции. Здесь ты бы просто спрашивал, что будем генерировать: HTML или JSON? И затем передавал бы управление соответствующей функции.

2018-10-16 10:56 UTC, TheDarkestDay commented on src/commands/server.js
> +        const currentErrMsg = `${cur.fieldName} ${cur.errorMessage}`;
Нормально.

2018-10-16 10:56 UTC, TheDarkestDay commented on src/commands/server/errors/illegal-argument-error.js
> +class IllegalArgumentError extends Error {
Семантика `IllegalArgument` и `ValidationError` слишком похожа - поэтому, чтобы не путаться, я предлагаю просто завести класс `BadRequest` для всех ошибок подобного рода.

2018-10-16 10:56 UTC, TheDarkestDay commented on src/commands/server/routes/offers-router.js
> +    throw new IllegalArgumentError(`date should be number`);
Bad Request (см. комментарий выше)

2018-10-16 10:56 UTC, TheDarkestDay commented on test/server.test.js
> +  it(`with real date responds with an object with the same date which was in the request`, async () => {
Судя по обсуждениям в `mocha` данный пакет больше не завершает процесс по завершению всех тестов - для этого поведения нужно воспользоваться опцией `--exit`.

2018-10-19 04:03 UTC, TheDarkestDay requested changes

2018-10-19 04:03 UTC, TheDarkestDay commented on src/commands/server/errors-formatter.js
> +  return errors.length ? errors : [{code, error, errorMessage}];
Есть какая-то причина, чтобы передавать именно массив с одним объектом, а не сразу объект? Клиенту с таким API явно будет работать удобнее.

2018-10-19 04:03 UTC, TheDarkestDay commented on src/commands/main.js
> +      const entities = Array.from({length: entitiesCount}, () => generateEntity(entity));
С этим будем что-нибудь делать или оставим как есть?

2018-10-19 04:03 UTC, TheDarkestDay commented on src/commands/server/routes/offers-router.js
> +  const from = skip || 0;
Значения по-умолчанию для параметров стоит вынести в константы.

2018-10-19 04:03 UTC, TheDarkestDay commented on test/server.test.js
> +  it(`responds with an object where offers length less or equals to limit`, () => {
Не хватает аналогичного теста для проверки работы параметра `skip` (непосредственно "пропускание" элементов).

2018-10-19 04:03 UTC, TheDarkestDay commented on test/server.test.js
> +        assert.ok(responseKeys.every((i) => body[i] !== undefined), `every key in the response object shouldn't represent undefined`);
Немного сбивает с толку, что в других тестах ты аналогичных проверок не делаешь, хотя они достаточно универсальные и могли быть, теоретически, в любом тесте.

2018-10-19 04:03 UTC, TheDarkestDay commented on src/commands/server/validate.js
> +const validate = (data, test) => {
Это хорошо, что ты уже начал разрабатывать универсальное решение для валидации чего-либо (хотя она нам понадобится только в одном из следующих заданий), но как я сейчас вижу, с текущим API валидировать целые объекты нашей предметной области (объявления о продаже) будет валидировать крайне сложно. 

В идеале хотелось бы иметь один метод `validate`, который бы принимал на вход объект для валидации,  и некоторый объект-схему, который задавал бы правила валидации для полей объекта (типа как в библиотеках joi или class-validator или даже в нашем объекте `generator-options`).

Пока, наверное, можно оставить все как есть, однако в задании о валидации сущностей, скорее всего, придется все основательно переписать.

2018-10-19 04:03 UTC, TheDarkestDay commented on src/commands/server/routes/offers-router.js
> +    limit: till,
Здесь закрался небольшой баг - в ответе сервера все заполненные параметры (skip, limit) приходят в виде строк.

2018-10-19 06:53 UTC, RayProud commented on src/commands/main.js
> +      const entities = Array.from({length: entitiesCount}, () => generateEntity(entity));
Я предлагаю оставить. Мне больше Array.from нравится. Его даже Facebook использует в примерах в доках React.

2018-10-19 06:53 UTC, RayProud commented on src/commands/server/errors-formatter.js
> +  return errors.length ? errors : [{code, error, errorMessage}];
Это требование из ТЗ HTML академии.

2018-10-19 06:55 UTC, RayProud commented on src/commands/server/validate.js
> +const validate = (data, test) => {
Да я как раз из-за этого так много времени и делал. Потому что не мог найти баланс между нормальной валидацией и каким-то понятным API. Предлагаю потом переписать.

2018-10-19 06:57 UTC, RayProud commented on src/commands/server/errors-formatter.js
> +  return errors.length ? errors : [{code, error, errorMessage}];
В пункте `Некорректные запросы` есть следубщий пример:

```
[
	{
	  "error": "Internal Error",
		"errorMessage": "Server has fallen into unrecoverable problem."
	}
]
```

2018-10-19 07:18 UTC, RayProud commented on src/commands/server/routes/offers-router.js
> +  const from = skip || 0;
Сделал

2018-10-19 07:18 UTC, RayProud commented on test/server.test.js
> +  it(`responds with an object where offers length less or equals to limit`, () => {
Добавил

2018-10-19 07:18 UTC, RayProud commented on test/server.test.js
> +        assert.ok(responseKeys.every((i) => body[i] !== undefined), `every key in the response object shouldn't represent undefined`);
Вынес в функцию в этом же файле (пока вроде нигде больше не нужна) и добавил в остальные тесты.

2018-10-19 07:18 UTC, RayProud commented on src/commands/server/routes/offers-router.js
> +    limit: till,
Поправил.

2018-10-19 08:48 UTC, TheDarkestDay approved these changes

2018-10-19 08:48 UTC, TheDarkestDay commented on src/commands/main.js
> +      const entities = Array.from({length: entitiesCount}, () => generateEntity(entity));
Хорошо.

2018-10-19 08:48 UTC, TheDarkestDay commented on src/commands/server/errors-formatter.js
> +  return errors.length ? errors : [{code, error, errorMessage}];
Хорошо.

2018-10-19 08:48 UTC, TheDarkestDay commented on src/commands/server/validate.js
> +const validate = (data, test) => {
Договорились.

2018-10-19 08:49 UTC, merged