Module5 task3
htmlacademy-nodejs/22908-keksobooking pull request #12
Opened 2018-10-21 11:09 UTC by RayProud

2018-10-22 16:22 UTC, RayProud commented on src/commands/server/validation/validate.js
> +            error: `Validation Error`,
Вот здесь можно выставлять одну ошибку для всех. И таким образом убрать дублирование логики.

2018-10-22 16:22 UTC, RayProud commented on test/server.test.js
> +        return request(app)
Такое разбиение на разные тесты — это нормально? В итоге, я использую один объект с невалидными полями, но проверяю все вадидации по отдельности. Кажется, это то, что нужно.

2018-10-23 03:43 UTC, TheDarkestDay requested changes

2018-10-23 03:43 UTC, TheDarkestDay commented on src/config.js
> +        if (allowedValues.indexOf(values[i]) === -1) {
Эту проверку можно переписать более лаконично с помощью метода массива `some`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/config.js
> +        if (allowedValues.indexOf(values[i]) === -1) {
Эту проверку можно переписать более лаконично с помощью метода массива `some`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/config.js
> +        if (allowedValues.indexOf(values[i]) === -1) {
Эту проверку можно переписать более лаконично с помощью метода массива `some`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/config.js
> +        if (allowedValues.indexOf(values[i]) === -1) {
Эту проверку можно переписать более лаконично с помощью метода массива `some`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/routes/offers-router.js
> +  validateUsingAScheme(makeObjectToValidate(req.query), getOffersScheme);
Почему бы теперь не переименовать этот метод в просто `validate`?

2018-10-23 03:43 UTC, TheDarkestDay commented on .eslintrc.yml
> +  ecmaVersion: 2018
Для чего тебе потребовалось сменить версию языка? Для spread-оператора в объектах?

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/validation/rules.js
> +/* eslint-disable consistent-return */
`consistent-return` - хорошее правило, не стоит им пренебрегать. Явное в большинстве случаев лучше неявного, а это правило заставляет нас писать функции, отвечающие определенному интерфейсу, который говорит, что функция обязательно что-нибудь вернет, если хоть один путь исполнения в ней что-то возвращает.

Часто в подобных функциях в случае успеха валидации возвращают либо `null`, либо `true`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/validation/rules.js
> +  isArrayOfUniqueValues(value, shouldBeAnArrayOfUniqueValues) {
Эти функции лучше объявить во вне, и затем экспортировать, чтобы избежать боли в случае, если тебе понадобится, например, вызвать внутри `isArrayOfUniqueValues` функцию `isNumeric`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/validation/rules.js
> +  type(value, type) {
Нужно имена функций привести в соответствие критериям (в них должны быть глаголы).

2018-10-23 03:43 UTC, TheDarkestDay commented on test/server.test.js
> +        return request(app)
Да, все в порядке. Только не забывай перезаписывать данные в `beforeEach`, чтобы у тестов не было общего состояния.

2018-10-23 03:43 UTC, TheDarkestDay commented on test/server.test.js
> +      it(`responds with type error in json`, () => {
В описании теста лучше упомянуть какую-именно валидацию ты пытаешься проверить (можно прямо на языке предметной области правило описать).

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/routes/offers-router.js
> +  validateUsingAScheme(makeObjectToValidate(req.params), getOfferScheme);
Разве нельзя передать в этот метод сразу же `req.params`?

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/validation/validate.js
> +function makeObjectToValidate(source) {
Кажется, этот метод даже не нужен - примерно то же самое можно сделать с помощью `Object.assign`.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/validation/validate.js
> +            error: `Validation Error`,
Да.

2018-10-23 03:43 UTC, TheDarkestDay commented on src/commands/server/validation/rules.js
> +    if (shouldBeAnImage && (!mimetype || !(/image/gi.test(mimetype)))) {
Смущают все эти булевы флаги типа `shouldBeAnImage` и `shouldBeAnArrayOfUniqueValues`. Зачем мы тогда начали выполнение этой функции, если уже сразу было известно, что для этого значения данное правило валидации применятся не должно? Может, эту логику можно как-нибудь перенести в `validate`?

2018-10-23 04:21 UTC, RayProud commented on test/server.test.js
> +        return request(app)
А что переписывать? Объекты, которыю шлю POST'ом?

2018-10-23 04:22 UTC, RayProud commented on .eslintrc.yml
> +  ecmaVersion: 2018
Для spread, да. Иначе eslint не понимал, что это такое.
Хотя spread поддерживается в node без флагов начиная с 8.3.

2018-10-23 04:23 UTC, RayProud commented on src/commands/server/validation/rules.js
> +/* eslint-disable consistent-return */
Окей, тогда перепишу на null. Как смысл того, что ошибки нет. В обратном случае пусть возвращает ошибку.

2018-10-23 04:26 UTC, RayProud commented on src/commands/server/routes/offers-router.js
> +  validateUsingAScheme(makeObjectToValidate(req.params), getOfferScheme);
Еще вчера ночью у меня было какое-то оправдание, но сейчас я не могу понять, почему я просто не передаю params или query.

В общем, функция makeObjectToValidate тоже становится не нужной.

2018-10-23 04:26 UTC, RayProud commented on src/commands/server/validation/validate.js
> +function makeObjectToValidate(source) {
Удалю её. Можно сразу передавать params или query.

2018-10-23 04:29 UTC, RayProud commented on src/commands/server/validation/rules.js
> +    if (shouldBeAnImage && (!mimetype || !(/image/gi.test(mimetype)))) {
Это было для единства. Функция-валидатор принимает значение и свой конфиг.
Но в случае булевых значений, кажется, смысла всё же нет. Писать в схеме `isReauired: false` бессмысленно.

Уберу.

2018-10-23 14:25 UTC, RayProud commented on src/commands/server/validation/rules.js
> +  type(value, type) {
Переписал

2018-10-23 14:26 UTC, RayProud commented on src/commands/server/validation/rules.js
> +  isArrayOfUniqueValues(value, shouldBeAnArrayOfUniqueValues) {
Вынес

2018-10-23 14:26 UTC, RayProud commented on src/commands/server/routes/offers-router.js
> +  validateUsingAScheme(makeObjectToValidate(req.query), getOffersScheme);
Переименовал

2018-10-23 14:26 UTC, RayProud commented on src/config.js
> +        if (allowedValues.indexOf(values[i]) === -1) {
Сделал

2018-10-23 16:13 UTC, RayProud commented on test/server.test.js
> +        return request(app)
Сделал

2018-10-24 04:37 UTC, TheDarkestDay requested changes

2018-10-24 04:37 UTC, TheDarkestDay commented on src/commands/server/validation/rules.js
> +        errorMessage: `doesn't fit the expected format`,
Может, мы теперь можем отсюда просто возвращать сообщение об ошибке, не в виде объекта? Тогда и spread для объектов нам не понадобится больше - можно будет настройки линтера вернуть в оригинальный вид.

2018-10-24 04:37 UTC, TheDarkestDay commented on test/server.test.js
> +      it(`responds with error in json — features should be array of unique allowed values`, () => {
Описание тестов некорректное (там json закрался).

2018-10-24 04:47 UTC, RayProud commented on src/commands/server/validation/rules.js
> +        errorMessage: `doesn't fit the expected format`,
Отличная мысль! Объект здесь уже и не нужен.

2018-10-24 04:50 UTC, RayProud commented on test/server.test.js
> +      it(`responds with error in json — features should be array of unique allowed values`, () => {
Тут имеется в виду формат ответа.
Ниже ответ в html.

2018-10-24 04:52 UTC, RayProud commented on src/commands/server/validation/rules.js
> +        errorMessage: `doesn't fit the expected format`,
Сделал

2018-10-24 05:02 UTC, TheDarkestDay approved these changes

2018-10-24 05:02 UTC, merged