Module6 task1
htmlacademy-nodejs/22908-keksobooking pull request #13
Opened 2018-10-23 18:36 UTC by RayProud

2018-10-27 18:57 UTC, RayProud commented on package.json
> +    "buffer-to-stream": "1.0.0",
Сделал как было в лекции (там использовали эту библиотеку) просто потому что очень много времени переписывал всё остальное. Просто не успеваю написать своё и протетсировать.

Можно оставить на конец.

2018-10-27 18:57 UTC, RayProud commented on src/commands/main.js
> +const generateEntity = require(`../../test/mocks/generator/generate-entity`);
По аналогии с учебным проектом вынес в тесты/моки.

2018-10-27 18:57 UTC, RayProud commented on src/server/errors/index.js
> +module.exports = {
На работе привык делать в папках `index.js`, потому что потом удобно делать деструктуризацию из папки. Не надо к каждому отдельному файлу прописывать require.

2018-10-27 18:57 UTC, RayProud commented on src/server/index.js
> +app.use(`/`, defaultRouter);
Решил максимально разнести логику на роуты. 
Теперь этот файл действительно просто команда, которая запускает экспресс с несколькими роутами.

А вот сами роуты можно спокойно тестировать (что я ниже и сделал).

2018-10-27 18:57 UTC, RayProud commented on src/server/middlewares/error.js
> +        res.status(400).json(err.message);
Честно говоря, не знаю, как мне это обрабатывать.

В идеале, нужно несколько ошибок обрабатывать по кодам ошибок Монги, чтобы была какая-то смысловая нагрузка.
Но на это пока просто не хватило времени. Плюс, у меня нет кейса, когда нельзя добавить два одинаковых объявления — это будут два разные объявления, хоть и с похожими данными.

Если есть предложения (и кейсы того, что может упасть) — с радостью сделаю. Но лучше попозже 🙏

2018-10-27 18:57 UTC, RayProud commented on src/server/routes/offers/default.js
> +  `Pavel`,
Прочитал в ТЗ, что имя должно автоматически проставляться, если не пришло.
Вроде больше нигде не нужно, поэтому оставил этот список здесь.

2018-10-27 18:57 UTC, RayProud commented on src/server/routes/offers/default.js
> +      {},
Только чистые функции! Никаких мутаций пришедших объектов, чтобы избежать неожиданностей!
Поэтому `Object.assign`.

О том, почему нужна эта функция — пишу дальше.

2018-10-27 18:57 UTC, RayProud commented on src/server/routes/offers/default.js
> +    const {address} = body;
Кажется, что тут может упасть деструктуризация, но на самом деле `validate` быстрее выкинет ошибку, потому что это поле обязаьтельное. И если его нет, то до этого момента не дойдёт.

2018-10-27 18:57 UTC, RayProud commented on src/server/routes/offers/default.js
> +    validatedOffer.location = location;
Согласно ТЗ, если валидация прошла, то в ответ мы должны вернуть тот же объект, что нам прислали, но с полем location.

2018-10-27 18:57 UTC, RayProud commented on src/server/routes/offers/default.js
> +    const objectToSave = prepareOfferForSave(validatedOffer);
А вот в базе, согласно той же документации, мы уже должны хранить объекты с другой структурой. Где отдельно есть поля `date` и `author`, в добавок к тем, что есть. Поэтому такое разбиение.

Пример Request:
GET /offers/1519136255300:
```
{
  "author": {
    "name": "Pavel",
    "avatar": "api/offers/1519136255300/avatar"
  },
  "offer": {
    "title": "Маленькая квартирка рядом с парком",
    "address": "471, 545",
    "description": "Маленькая чистая квратира на краю парка. Без интернета, регистрации и СМС.",
    "price": 30000,
    "type": "flat",
    "rooms": 1,
    "guests": 1,
    "checkin": "9:00",
    "checkout": "7:00",
    "features": ["elevator", "conditioner"]
  },
  "location": {
    "x": 471,
    "y": 545
  },
  "date": 1519136255300
}
```

2018-10-27 18:57 UTC, RayProud commented on src/server/routes/offers/default.js
> +    validatedOffer.location = location;
Пример:
Request:
POST /offers
```
{
  "name": "Pavel",
  "title": "Маленькая квартирка рядом с парком",
  "address": "570, 472",
  "description": "Маленькая чистая квратира на краю парка. Без интернета, регистрации и СМС.",
  "price": 30000,
  "type": "flat",
  "rooms": 1,
  "guests": 1,
  "checkin": "9:00",
  "checkout": "7:00",
  "features": ["elevator", "conditioner"]
}
```

Response:
200 OK
```
{
  "name": "Pavel",
  "title": "Маленькая квартирка рядом с парком",
  "address": "570, 472",
  "description": "Маленькая чистая квратира на краю парка. Без интернета, регистрации и СМС.",
  "price": 30000,
  "type": "flat",
  "rooms": 1,
  "guests": 1,
  "checkin": "9:00",
  "checkout": "7:00",
  "features": ["elevator", "conditioner"],
  "location": {
    "x": 570,
    "y": 472
  }
}
```

2018-10-27 18:57 UTC, RayProud commented on src/server/stores/images-store.js
> +      return void 0;
Из лекции.

2018-10-27 18:57 UTC, RayProud commented on src/server/stores/images-store.js
> +      chunkSizeBytes: 512 * 1012,
Здесь магические числа тоже из лекции.
Можно в константы вынести, наверное.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/rules.js
> -    if (type === `number` && isNumeric(value)) {
Вынес эту логику в `validate`. Кажется, здесь лучше просто проверять, а не преобразовывать и додумывать.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/schemes/post-offer.js
> +  description: {
Почему-то в доке нет указаний про это поле.
Оно есть в примерах `GET`, но нет ничего про его ограничения. Додумал сам.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/schemes/post-offer.js
> +    testType: `number`,
Про `guests` почему-то тоже нет требований. Дописал как придумал.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/schemes/post-offer.js
> +    testMask: /^\d+,\s*\d+$/
Убрал флаги, потому что `i` для чисел роли не играет, а только путает. 
А вот `g` заставляет регулярку запоминат lastIndex и у меня ломается проверка.

2018-10-27 18:57 UTC, RayProud commented on test/default-route.test.js
> +app.use(`/`, defaultRouter);
Сделал отдельные тесты на `/`. А те, что были, теперь тестируют `api/offers`.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/validate.js
> +  if (currentScheme.testType === `number` && isNumeric(value)) {
В комментарии попытался описать потребность в этой функции.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/validate.js
> +  return validatedObj;
Теперь возвращаю отсюда объект (как и предлагали на лекциях).
Так удобнее записывать в базу уже отформатированные объекты, без лишних полей, которых нет в схеме, и в том типе, который должен быть, а не как из multipart/form-data приходит. Кстати, на этот баг наткнулся благодаря тестам! Это круто, я считаю.

2018-10-27 18:57 UTC, RayProud commented on test/api-offers.test.js
> +const offersRouter = require(`../src/server/routes/offers`)(offersStoreMock, imagesStoreMock);
Теперь в тестах тестируются отдельные роуты.

2018-10-27 18:57 UTC, RayProud commented on test/api-offers.test.js
> +    describe(`of JSON`, () => {
Немного поменял схему describe, чтобы легче было дебажить.

2018-10-27 18:57 UTC, RayProud commented on src/server/validation/validate.js
> +    if (isNil(value) && !currentScheme.isRequired) {
Оказывается, у меня всё это время не работала проверка на `isRequired`. Пофиксил.
В тестах тоже много переписал.

2018-10-27 18:57 UTC, RayProud commented on test/api-offers.test.js
> +          name: `Roman`,
Объекты все отличаются, поэтому в каждом `it` завожу новый.

Сперва хотел мутировать их внутри `it`, но вроде так делать нельзя — держать какую-то логику в тестах. Поэтому сделал максимально топорно.

2018-10-27 18:57 UTC, RayProud commented on test/api-offers.test.js
> +    it(`responds with an image`, async () => {
Вот что я не понял — как тестировать на моках добавление картинки? Поэтому заскипал.
Мне кажется, что с тестовой базой (вместо моков) эти тесты имели бы больший смысл.

2018-10-28 11:06 UTC, TheDarkestDay requested changes

2018-10-28 11:06 UTC, TheDarkestDay commented on src/server/middlewares/error.js
> +        res.status(400).json(err.message);
Особо тут кейсы не придумаешь - у нас всего одна сущность, ни в каких отношениях она не состоит, и валидация всех полей осуществляется перед записью. Соответственно, у нас остается пласт ошибок в работе с самой Mongo:  проблемы с соединением, нехватка места/прав/чего-нибудь еще. Поэтому, лучше здесь использовать код 500, потому что природа этой ошибки чисто серверная - от клиента она никак не зависит.

2018-10-28 11:06 UTC, TheDarkestDay commented on src/database/db.js
> +const url = `mongodb://localhost:27017`;
`url` тоже можно записать в константном регистре.

2018-10-28 11:06 UTC, TheDarkestDay commented on src/server/routes/offers/default.js
> +  offersRouter.post(`/`, jsonParser, upload.single(`avatar`), asyncMiddleware(async (req, res) => {
Заметил, что не работает загрузка изображения в поле `preview`.

2018-10-28 11:06 UTC, TheDarkestDay commented on src/server/routes/offers/default.js
> +  `Pavel`,
Хорошо.

2018-10-28 11:23 UTC, TheDarkestDay commented on test/api-offers.test.js
> +    it(`responds with an image`, async () => {
Нужно сконфигурировать заглушку так, чтобы она отдала нужное изображение, если её кто-нибудь попросит. Например, можно просто завести объект, который бы хранил в себе тестовые аватары для тестовых объявлений. Этот объект внутри себя использовал бы `ImageStoreMock` для того, чтобы эмулировать отдачу нужных картинок.

2018-10-28 11:34 UTC, RayProud commented on src/server/routes/offers/default.js
> +  offersRouter.post(`/`, jsonParser, upload.single(`avatar`), asyncMiddleware(async (req, res) => {
Добавил.

2018-10-28 11:34 UTC, RayProud commented on src/database/db.js
> +const url = `mongodb://localhost:27017`;
Поменял.

2018-10-28 11:37 UTC, RayProud commented on src/server/middlewares/error.js
> +        res.status(400).json(err.message);
Поменял на 500.

2018-10-28 12:24 UTC, merged