Хлебные крошки
htmlacademy-nodejs/22908-keksobooking pull request #14
Opened 2018-10-28 14:27 UTC by RayProud

---
:mortar_board: [Хлебные крошки](https://up.htmlacademy.ru/nodejs/2/user/22908/tasks/17)

2018-10-28 14:31 UTC, RayProud commented on src/commands/main.js
> +    console.log(GREETING);
Не понял, почему в учебном проекте все console.log заменили на logger. 
В задании явно написано 
```
Замените все использования console.log и console.error на использование логгера. Кроме тех, мест где это нужно для общения с CLI интерфейсом.
```

То есть, в наших командах надо оставить console.log. В остальных местах использовал logger.

2018-10-28 14:31 UTC, RayProud commented on src/server/middlewares/error.js
> +        logger.error(err);
Так как юзеру 500-е ошибки показываются без подробностей, то в dev-режиме я хотел бы посмотреть на них в консоле.

2018-10-29 03:34 UTC, TheDarkestDay requested changes

2018-10-29 03:34 UTC, TheDarkestDay commented on src/server/middlewares/error.js
> +        logger.error(err);
Мы ведь в любом случае хотим залоггировать эту ошибку, будь то среда эксплуатации или разработки. Если я все верно понимаю, это условие нам даже не нужно: достаточно просто вызвать метод логгера, а канал доставки уже будет определен правильно, в зависимости от окружения (и на development-окружении эта ошибка как раз попадет в консоль).

2018-10-29 03:34 UTC, TheDarkestDay commented on src/logger.js
> +if (process.env.NODE_ENV !== `production`) {
Можно еще добавить конфигурацию логгера-пустышки для тестов, чтобы вывод результатов было проще читать.

2018-10-29 03:35 UTC, RayProud commented on src/server/middlewares/error.js
> +        logger.error(err);
Согласен. Уберу.

2018-10-29 03:44 UTC, RayProud commented on src/logger.js
> +if (process.env.NODE_ENV !== `production`) {
Добавил.

2018-10-29 06:44 UTC, TheDarkestDay requested changes

2018-10-29 06:44 UTC, TheDarkestDay commented on src/logger.js
> +if (process.env.NODE_ENV !== `production`) {
Осталось только сделать так, чтобы на время тестов `process.env.NODE_ENV` устанавливался в `test`, чтобы это все работало. Самый наивный способ - самому переписывать переменную окружения в каждом тесте. 

Гораздо лучше передавать переменную окружения в npm-скрипте `test`, однако тут возникнет проблема с кросс-платформенностью (переменные в командной строке в разных ОС записываются по разному). Можно воспользоваться пакетом [cross-env](https://www.npmjs.com/package/cross-env) для этих целей.

Еще нужно что-нибудь уже сделать с тестом получения картинки - либо реализовать, либо удалить (он сейчас висит в результатах как pending).

2018-10-29 07:02 UTC, RayProud commented on src/logger.js
> +if (process.env.NODE_ENV !== `production`) {
Добавил cross-env. 

Тест решил всё-таки убрать.

2018-10-29 09:56 UTC, merged