Add some CLI
htmlacademy-nodejs/22908-keksobooking pull request #2
Opened 2018-09-27 08:39 UTC by RayProud

2018-09-27 09:21 UTC, TheDarkestDay requested changes

2018-09-27 09:21 UTC, TheDarkestDay commented on index.js
> +    process.exit(0);
Процесс и без того завершится с кодом успеха (0) в случае, если мы нигде в программе не вышли с каким-то другим кодом. Поэтому, конкретно в этом месте этот вызов избыточен.

Возможно, ты это сделал, чтобы избежать использование `break` для остановки выполнения после очередного `case`-блока, однако я предложил бы все-таки использовать `break` (опять же, из-за избыточности `process.exit(0)`).

2018-09-27 09:21 UTC, TheDarkestDay commented on index.js
> +--help    — печатает этот текст;
Можно сделать немного гибче: хранить все доступные команды в какой-нибудь структуре, где каждой команде соответствовал бы объект с двумя полями:
1. Функция с логикой работы команды
2. Краткая справка по команде

Тогда необходимо будет немного изменить логику отображения списка всех доступных команд, однако, в таком приложении будет гораздо проще добавлять новые команды (достаточно будет просто добавить новый объект в соответствующую структуру).

2018-09-27 20:05 UTC, RayProud commented on index.js
> +--help    — печатает этот текст;
Согласен. Пофиксил.

2018-09-27 20:06 UTC, RayProud commented on index.js
> +    process.exit(0);
Пофиксил.

2018-09-27 20:07 UTC, RayProud commented on index.js
> +      console.log(this.info);
Может показаться, что тут везде дублирование, но это просто совпадение. То, что у всех этих команд action — сделать console.log от info не значит, что у других тоже так будет.

Решил, что для этого не стоит создавать какой-то отдельный метод.

2018-09-28 03:13 UTC, TheDarkestDay requested changes

2018-09-28 03:13 UTC, TheDarkestDay commented on index.js
> +    info: 'Доступные команды:\n--help    — печатает этот текст;\n--version — печатает версию приложения;',
Когда я говорил о справочной информации о команде, я имел в виду короткий текст, который описывает то, что данная команда делает. Например, для `--help` это `печатает этот текст`, для `--version` - `печатает версию приложения`. C такой структурой нам удастся сделать вывод списка всех команд гибким: он просто будет пробегаться в цикле по всем ключам объекта `commands` и выводить в консоль имя текущей команды и её справку. Нам не придется в ручную вбивать текст каждой новой команды в поле `info` команды `--help`.

2018-09-28 03:13 UTC, TheDarkestDay commented on index.js
> +    action: function() {
По критериям HTMLAcademy, функции должны называться глаголами.

2018-09-28 06:37 UTC, RayProud commented on index.js
> +    info: 'Доступные команды:\n--help    — печатает этот текст;\n--version — печатает версию приложения;',
> я имел в виду короткий текст, который описывает то, что данная команда делает

Это было неочевидно из предыдущего комментария.

> он просто будет пробегаться в цикле по всем ключам объекта commands и выводить в консоль имя текущей команды

Тогда из этого объектв нужно будет убрать `default` и `error`, либо в логике формирования текста help'а как-то это обрабатывать.

> . Нам не придется в ручную вбивать текст каждой новой команды в поле info команды --help

Так как эта информация нигде, кроме `--help` не используется, то и вносить её придётся только один раз. То есть, её можно держать в этой строке. Когда как динамическое формирование строки, которое ты предоожил, постоянно будет проходиться по объекту и выполнять действие, которое не нужно. Это программирование для программирования.

2018-09-28 06:39 UTC, RayProud commented on index.js
> +    action: function() {
Fix

2018-09-28 07:00 UTC, RayProud commented on index.js
> +    info: 'Доступные команды:\n--help    — печатает этот текст;\n--version — печатает версию приложения;',
Всю эту логику можно будет реализовать дальше в рамках https://up.htmlacademy.ru/nodejs/2/tasks/5.

2018-09-28 09:57 UTC, TheDarkestDay requested changes

2018-09-28 09:57 UTC, TheDarkestDay commented on index.js
> +    info: 'Доступные команды:\n--help    — печатает этот текст;\n--version — печатает версию приложения;',
Хорошо, реализуем в рамках следующих задач. 

Не согласен с тем, что это "не нужно", но не буду настаивать. Перед нами в рамках интенсива поставлен ряд задач, и я бы хотел, чтобы мы решали их не только быстро и корректно, но и думая о поддерживаемости и удобства внесения изменений в случае изменяющихся требований.

Понятно, что все эти изменения  - чисто теоретические и накручивать их можно до бесконечности. Однако, если есть решение, превосходящее другие по поддерживаемости и расширяемости, и при этом сложность его реализации не превышает разумные пределы, то я бы порекомендовал использовать его.

2018-09-28 09:57 UTC, TheDarkestDay commented on index.js
> +    getInfo: function() {
Возможно, я снова неправильно выразился, но я подразумевал, что функции эти будут непосредственно содержать в себе логику работы команды. Сейчас, в принципе, это верно, однако название больше похоже на какой-то геттер для некого свойства `info`. Я бы посоветовал переименовать данный метод во что-нибудь типа `execute` или `run`.

2018-09-28 09:57 UTC, TheDarkestDay commented on index.js
> +  case '--help':
Эти литералы необходимо вынести в константы - можно занести их в перечисление типа `Command` или `CommandName`.

2018-09-28 20:56 UTC, RayProud commented on index.js
> +  case '--help':
Не понимаю, что такое `перечисление типа Command или CommandName`. Это объект с такими ключами и такими же значениями-строками?

Эти же значения используются в качестве ключей в объекте `commands`. Выходит, сделать там вычисляемые названия полей через `[commands['--help']]` и тд?

2018-09-28 21:02 UTC, RayProud commented on index.js
> +  case '--help':
Как можно не дублировать эти строки, на мой взгляд:

Сделать объект вида 
```
const commandsNames = {
  'help': '--help'
};
```

Использовать это в ключах `commands` и в switch-case:
```
const commands = {
  [commandsNames.help]: {
    info: 'Доступные команды:\n--help    — печатает этот текст;\n--version — печатает...'
  }
};

switch(cmd) {
  case commandsNames.help:
    ...
}
```

Но это опять похоже на программирование для программирования.

Проблема решится, когда мы перейдём на TypeScript и будем использовать Enum.

2018-09-29 03:24 UTC, TheDarkestDay requested changes

2018-09-29 03:24 UTC, TheDarkestDay commented on index.js
> +  case '--help':
В рамках интенсива мы не сможем перейти на TypeScipt (по крайней мере, на прошлом потоке по нему была лишь ознакомительная лекция).  Про то, как сделать перечисления в  JS, ты написал все правильно (только именуются они, как классы - с большой буквы).

Опять же, не очень понимаю, в чем здесь "программирование ради программирования". В текущем коде есть явная проблема -  при изменении какой-либо команды (например, мы захотим `--help` заменить на `--info`), нам придется производить замены в двух местах (еще и помнить нужно будет об этом). И проблема эта решается вынесением данных строковых литералов в константы (перечисление, в нашем случае).

2018-09-29 15:07 UTC, TheDarkestDay requested changes

2018-09-29 15:07 UTC, TheDarkestDay commented on index.js
> +  'help': '--help',
Думаю, нет особых причин помещать ключи этого объекта в кавычки.

2018-09-29 15:07 UTC, TheDarkestDay commented on index.js
> +const CommandsNames = {
Перечисления (как и классы) называют существительными в единственном числе.

2018-09-30 06:10 UTC, TheDarkestDay approved these changes

2018-09-30 06:10 UTC, merged