add eslint
htmlacademy-nodejs/22908-keksobooking pull request #3
Opened 2018-09-28 06:59 UTC by RayProud

2018-09-28 10:01 UTC, TheDarkestDay requested changes

2018-09-28 10:01 UTC, TheDarkestDay commented on .eslintrc.yml
> +parserOptions:
В логах сборки, доступных по [адресу](https://travis-ci.com/htmlacademy-nodejs/22908-keksobooking/builds/86245953) видно, что Eslint не запускается. Возможно, это потому, что ты не внес изменения в  `travis.yml`, согласно заданию.

2018-09-30 19:25 UTC, RayProud commented on .eslintrc.yml
> +parserOptions:
Извиняюсь, забыл закоммитить. 

Пофиксил.

2018-09-30 20:46 UTC, RayProud commented
@TheDarkestDay, слушай, а может препуш хуки поставить? А то тревис — это хоршо, но можно же вообще не разрешать пушить код, который потом всё равно упадёт (и не пройдёт CR).

2018-10-01 02:32 UTC, TheDarkestDay commented
> @TheDarkestDay, слушай, а может препуш хуки поставить? А то тревис — это хоршо, но можно же вообще не разрешать пушить код, который потом всё равно упадёт (и не пройдёт CR).

Хорошая идея. Если это много времени не займет, то дерзай.

2018-10-01 13:15 UTC, RayProud commented
Решили, что husky прикручивать не будем, как и писать башник для создания хуков локально.

2018-10-01 13:16 UTC, merged