colored some commands
htmlacademy-nodejs/22908-keksobooking pull request #5
Opened 2018-10-03 18:12 UTC by RayProud

2018-10-03 18:13 UTC, RayProud commented
Решил остальные команды не расскрашивать, чтобы быстрее пройти дальше.
Я и так отстаю.

2018-10-04 02:28 UTC, TheDarkestDay requested changes

2018-10-04 02:28 UTC, TheDarkestDay commented on src/help.js
> +const colors = require(`colors`);
Так как `colors` меняет прототип класса String, его достаточно импортировать в одном месте, чтобы его методы были доступны во всем проекте. Поэтому, я предложил бы сделать это где-нибудь в `index.js`.

2018-10-04 06:50 UTC, RayProud commented on src/help.js
> +const colors = require(`colors`);
Не, лучше тогда перейти на `colors/safe`

2018-10-04 06:57 UTC, RayProud commented on src/help.js
> +const colors = require(`colors`);
Странно, `colors/safe` не работает. Пишет `Cannot find module 'colors/safe'`.

А если вынести сейчас require в index.js, то я не смогу пользоваться явным синтаксисом `colors.`, потому что это будет переменная только внутри index.js, и придется везде у строк вызывать методы. Не доверяю всему, что лезет в прототипы.

2018-10-04 12:46 UTC, RayProud commented on src/help.js
> +const colors = require(`colors`);
Решается переустановкой.

2018-10-04 16:36 UTC, TheDarkestDay requested changes

2018-10-04 16:36 UTC, TheDarkestDay commented on package.json
> +    "colors": "1.3.2",
С точки зрения нашего проекта это все-таки зависимость, необходимая во время выполнения, а не только во время разработки. Необходимо перенести в `dependencies`.

2018-10-04 22:21 UTC, RayProud commented on package.json
> +    "colors": "1.3.2",
+

2018-10-05 02:43 UTC, TheDarkestDay approved these changes

2018-10-05 02:43 UTC, merged