add generate entity and tests
htmlacademy-nodejs/22908-keksobooking pull request #7
Opened 2018-10-07 07:48 UTC by RayProud

2018-10-07 07:49 UTC, RayProud commented
lodash в devDependencies,  потому что только в тестах пока что используется.

2018-10-07 12:39 UTC, TheDarkestDay requested changes

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +const shuffle = require(`lodash/shuffle`);
На интенсивах HTML Academy мы стараемся не использовать сторонние библиотеки кроме тех, что явно указаны в заданиях. Метод `shuffle` из lodash реализует достаточно простой  [алгоритм](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) , который без проблем можно реализовать самостоятельно.

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        console.log(`Object.values(map)`, Object.values(map));
Отладочные `console.log` необходимо удалить.

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +  return `https://robohash.org/${Math.random().toString(36).slice(2)}`;
Выражение `Math.random().toString(36).slice(2)` тоже стоит вынести в отдельную функцию, чтобы было ясно, что это не какая-то магия, а штука для генерации случайного хеша.

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +function generateTitle() {
Что в `generateTitle`, что в `generateCheckin` и в других похожих местах ты делаешь одно и то же - получаешь случайный элемент некоторого массива. Значит, вместо этих двух функций можно создать одну - она будет получать на вход массив, а возвращать - случайный элемент из него.

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +  return flatTitles[Math.floor(Math.random() * flatTitlesLength)];
Следующие операции у тебя тоже повторяются:
1. Получение случайного числа в произвольном интервале
2. Получение случайного числа в интервале от 0 до n

Для этих операций так же необходимо завести свои функции.

Обрати внимание, что все функции, которые у тебя получатся в ходе рефакторинга, будут достаточно общими и потенциально могут быть полезными и в других модулях приложения - значит, следует их вынести в отдельный модуль (скажем, некий `utils.js`).

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +  const xMin = 300;
Константы-примитивы записываются в snake-case.

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +
Выглядит это все довольно-таки многословно - почему бы не обойтись одной константой для семидневного интервала в формате Unix?

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +  const todayInUnix = Math.floor(+new Date() / 1000);
Получить текущую дату в представлении Unix можно с помощью `Date.now()`, не прибегая тем самым к хаку с приведением к числу с помощью унарного плюса.

2018-10-07 12:39 UTC, TheDarkestDay commented on src/generateEntity.js
> +function generateEntity() {
Почему бы не параметризировать эту функцию? Пускай она вход  принимает опции, влияющие на генерацию - например, максимальные/минимальные значения цены; возможные значения для features, checkin, checkout и др.

Таким образом, мы сделаем наши функции чище, избавив их от этих кусков внутреннего состояния, но еще и сделаем генерацию сущностей полностью настраиваемой.

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +const flatTitles = [`Большая уютная квартира`, `Маленькая неуютная квартира`, `Огромный прекрасный дворец`, `Маленький ужасный дворец`, `Красивый гостевой домик`, `Некрасивый негостеприимный домик`,
При применении рефакторинга из прошлого замечания все эти вещи перекочуют в отдельный модуль - `generator-options`, который затем можно будет использовать и из тестов, и из функции генерации.

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +/* eslint-disable max-nested-callbacks */
С ESlint-ом тут ничего не поделать - остается только отключать конкретное правило. Мне нравится структура вывода тестовых результатов, с ней все в порядке, поэтому можешь оставить, как есть.

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        assert.equal(entity.author.avatar.indexOf(`http`), 0);
Можно этот тест "прокачать" добавив проверку регулярным выражением на соответствие URL.

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +  const entity = generateEntity();
Необходимо перед каждым тестом генерировать новую сущность  - сделать это можно с помощью `beforeEach`. При текущей реализации есть проблема разделенного состояния между разными тестами - один тест может упасть из-за изменений, внесенных в состояние другим тестом (намеренных или не очень).

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        assert.equal(typeof entity.offer.price, `number`);
В похожих местах ты выносил проверку на тип в отдельный `it`. Для единообразия, нужно придерживаться одного подхода.

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        assert.equal(({}).toString.call(offerFeatures), `[object Array]`, `it's not an array`);
Разве нельзя проверку на массив реализовать с помощью метода `Array.isArray`?

2018-10-07 12:39 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        const map = offerFeatures.reduce((prev, cur) => {
Проверить на уникальность значений можно проще: просто положить в `Set` весь массив, а потом сравнить `size` set-а c длинной исходного массива. Так как `Set` не хранит дубликаты, то при неравенстве будет ясно, что в массиве не все элементы уникальны.

2018-10-07 15:33 UTC, RayProud commented on test/generateEntity.test.js
> +        assert.equal(({}).toString.call(offerFeatures), `[object Array]`, `it's not an array`);
Что здесь, что с Set —  постоянно забываю, что код не изоморфный и не пойдёт потом на клиент. Поправлю.

2018-10-07 15:34 UTC, RayProud commented on src/generateEntity.js
> +
Не, регулярками URL проверять не очень.
В node.js есть модуль 'url'.

2018-10-07 15:36 UTC, RayProud commented on src/generateEntity.js
> +  return flatTitles[Math.floor(Math.random() * flatTitlesLength)];
Про это я как раз в тг писал.

Во втором коммите вынес в отдельные функции. Надо теперь в `utils.js` вынести.

Но! Надо же и на них тесты на писать? Если да, то не будет ли дублирования, от того, что я одну и ту же функциональность в двух местах буду проверять?

2018-10-07 15:37 UTC, RayProud commented on test/generateEntity.test.js
> +        assert.equal(entity.author.avatar.indexOf(`http`), 0);
Не, регулярками URL проверять не очень.
В node.js есть модуль url.

2018-10-07 16:23 UTC, RayProud commented on test/generateEntity.test.js
> +/* eslint-disable max-nested-callbacks */
Ок.

2018-10-07 16:25 UTC, RayProud commented on test/generateEntity.test.js
> +  const entity = generateEntity();
Я думал про жизненный цикл теста, но не придумал, как это здесь использовать.

Вроде бы в моих тестах нет никаких мутаций, поэтому не должно ничего падать. Или я что-то упустил?

2018-10-07 17:07 UTC, RayProud commented on src/generateEntity.js
> +const shuffle = require(`lodash/shuffle`);
+

2018-10-07 17:07 UTC, RayProud commented on src/generateEntity.js
> +  return `https://robohash.org/${Math.random().toString(36).slice(2)}`;
Fix

2018-10-07 17:07 UTC, RayProud commented on src/generateEntity.js
> +function generateTitle() {
Fix

2018-10-07 17:08 UTC, RayProud commented on src/generateEntity.js
> +  const xMin = 300;
Вынес в конфиг

2018-10-07 17:09 UTC, RayProud commented on src/generateEntity.js
> +
Иногда некоторые просят делать развёрнуто. Можно сказал, что сделал так уже по привычке.
Сделал константой один день в секундах, а вот количество дней будет приходить из конфига или от юзера.

2018-10-07 17:09 UTC, RayProud commented on src/generateEntity.js
> +function generateEntity() {
Судя по всему, это и нужно будет в Задании 9.

Перепишу.

2018-10-07 17:10 UTC, RayProud commented on test/generateEntity.test.js
> +const flatTitles = [`Большая уютная квартира`, `Маленькая неуютная квартира`, `Огромный прекрасный дворец`, `Маленький ужасный дворец`, `Красивый гостевой домик`, `Некрасивый негостеприимный домик`,
Про это хотел уточнить.

Сейчас я вынес в файл `config.js` и переиспользую. Это норм?

2018-10-07 17:45 UTC, RayProud commented on test/generateEntity.test.js
> +        assert.equal(typeof entity.offer.price, `number`);
Слушай, а может я перепишу вечерком это всё на TypeScript и мы перестанем в юнитах делать проверки, которыми должен заниматься язык?

Это не наброс, просто я с TS уже немного отвык от подобной надобности. Кажется, и код будет логичнее.

2018-10-07 17:57 UTC, RayProud commented on test/generateEntity.test.js
> +        assert.equal(entity.author.avatar.indexOf(`http`), 0);
Попробовал с ним сделать. Уже не уверен, что он идеален. Там нет статических методов для проверки, подходит ли строка под понятие URL. Потому что там слишком много всяких вариаций.

2018-10-07 17:58 UTC, RayProud commented on test/generateEntity.test.js
> +        const map = offerFeatures.reduce((prev, cur) => {
Fix

2018-10-07 17:58 UTC, RayProud commented on test/generateEntity.test.js
> +        assert.equal(({}).toString.call(offerFeatures), `[object Array]`, `it's not an array`);
Fix

2018-10-07 17:59 UTC, RayProud commented on src/generateEntity.js
> +  return flatTitles[Math.floor(Math.random() * flatTitlesLength)];
Запушил структуру, которую предлагаю.

Разделил хелперы на общие (не привязанные к чему-либо) и для entity. Кажется, логично.

2018-10-07 17:59 UTC, RayProud commented on test/generateEntity.test.js
> +        console.log(`Object.values(map)`, Object.values(map));
Fix

2018-10-07 18:00 UTC, RayProud commented on src/generateEntity.js
> +function generateEntity() {
В общем, сделаю параметризацию после твоего ревью, как с другими вопросами всё решится. Особенно, с конфигом.

2018-10-08 03:43 UTC, TheDarkestDay requested changes

2018-10-08 03:43 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        const featuresSet = new Set();
Конструктор `Set` принимает на вход массив элементов. То есть, можно руками туда ничего не добавлять, как ты делаешь далее.

2018-10-08 03:43 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +  const entityInstance = generateEntity();
Все еще необходимо сделать так, чтобы новая сущность генерировалась каждый раз перед каждым новым тестом (писал об этом, но почему-то обсуждение куда-то пропало). Сделать это можно с помощью `beforeEach`.

2018-10-08 03:43 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +        assert.equal(({}).toString.call(photos), `[object Array]`, `it's not an array`);
На 133 строке ты применил `isArray`, а здесь - нет.

2018-10-08 03:43 UTC, TheDarkestDay commented on src/config.js
> +  entity: {
С конфигом в принципе все в порядке. Единственное, чего хотелось бы добиться - это единообразия в стиле его описания. Тут есть два варианта, как по мне:
1. Можно просто заполнить объект константами, который как-либо ограничивают сущности (например, `MAX_PRICE, MIN_PRICE, FLAT_TYPES` и т.д.)
2. Можно описать примерно как сейчас, когда объект сам по форме повторяет сущность (ключи у него названы точно так же), а значения представляют из себя объекты, задающие правила валидации (например, у него есть ключи типа `min, max`).

Твое описание больше похоже на второй стиль, только остается подправить поля `flatTitles`, `types`, `locationRange`.

То есть, например, flatTitle необходимо переименовать в просто `title` (так называется соответствующее свойство у нашей сущности), а в качестве его значения указать объект с полем, скажем `values` равное массиву возможных значений заголовка нашей сущности.

2018-10-08 13:13 UTC, RayProud commented on src/generateEntity.js
> +  const todayInUnix = Math.floor(+new Date() / 1000);
Fix

2018-10-08 13:34 UTC, RayProud commented on test/generateEntity.test.js
> +        const featuresSet = new Set();
Fix

2018-10-08 13:34 UTC, RayProud commented on test/generateEntity.test.js
> +  const entityInstance = generateEntity();
Fix

2018-10-08 13:34 UTC, RayProud commented on test/generateEntity.test.js
> +        assert.equal(({}).toString.call(photos), `[object Array]`, `it's not an array`);
Fix

2018-10-08 13:34 UTC, RayProud commented on src/config.js
> +  entity: {
Пошел по второму пути

2018-10-09 02:37 UTC, TheDarkestDay requested changes

2018-10-09 02:37 UTC, TheDarkestDay commented on test/generateEntity.test.js
> +  let entityInstance = generateEntity();
Здесь тебе генерировать сущность уже не нужно. Или линтер просто ругается на непроинициализированную переменную?

2018-10-09 02:37 UTC, TheDarkestDay commented on src/generateEntity.js
> +function generateEntity() {
На данный момент все хорошо, можешь приступать.

2018-10-09 06:03 UTC, TheDarkestDay requested changes

2018-10-09 06:03 UTC, TheDarkestDay commented on src/helpers/entity.js
> +function generatePrice(price) {
Теперь можно избавиться от многих функций, заменив их соответствующими из модуля `helpers/common`:
1. Функции generatePrice, generateGuests, generateRooms меняем на прямое использование `getRandomNumberInRange`
2. Функции `generateType`, `generateTitle`, `generateCheckin`, `generateCheckout` меняем на прямое использование `getRandomItemFromArray`
3. Функцию `generatePhotos` меняем на прямое использование `shuffle`.
4. Функцию `getFeatures` тоже можно обобщить до функции, например, `getRandomSample`, которая принимала бы на вход массив и возвращала бы случайный перемешанный подмассив из него.

2018-10-09 06:05 UTC, RayProud commented on src/helpers/entity.js
> +function generatePrice(price) {
Согласен.

Сейчас запушу.

2018-10-09 06:12 UTC, RayProud commented on src/helpers/entity.js
> +function generatePrice(price) {
Поправил

2018-10-09 07:29 UTC, TheDarkestDay approved these changes

2018-10-09 07:29 UTC, merged