add naive ask and write
htmlacademy-nodejs/22908-keksobooking pull request #8
Opened 2018-10-09 17:21 UTC by RayProud

2018-10-09 17:30 UTC, RayProud commented on src/commands/greet.js
> +  return new Promise((resolve) => rl.question(question, (answer) => resolve(answer)));
Это норм?

Я не смог придумать, как это обернуть через `promisify`.

2018-10-09 17:30 UTC, RayProud commented on src/commands/greet.js
> +    process.exit(1);
Вот тут я бы хотел перезадать вопрос, но с `async/await` не получается придумать, как это сделать.

Как вариант, решил выходить из программы.

2018-10-09 17:48 UTC, RayProud commented on src/commands/greet.js
> +    console.log(`See ya next time!`);
Можно еще `colors` использовать для успеха и ошибок.

2018-10-09 17:48 UTC, RayProud commented on test/generate-entity.test.js
> +const generateEntity = require(`../src/generate-entity`);
Модули же должны называться через дефис. Поэтому переименовал.

2018-10-09 17:48 UTC, RayProud commented on src/commands/greet.js
> +  async execute() {
Как ты думаешь, для этого отдельный модуль нужно сделать? И что вообще должно быть с модулем `greet`? Может быть его надо удалить вообще, а вместо него использовать новый, например, `data-generator`?

2018-10-09 17:48 UTC, RayProud commented on src/commands/greet.js
> +async function checkAndWrite(fileDir, entities) {
Пытался сразу тесты написать, но долго не мог понять, как вообще такое будет работать, поэтому сперва решил показать тебе на предмет адекватности.

2018-10-10 04:14 UTC, TheDarkestDay requested changes

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +  return new Promise((resolve) => rl.question(question, (answer) => resolve(answer)));
Да, все правильно, поскольку `question` не подходит по интерфейсу для работы с `promisify`.

2018-10-10 04:14 UTC, TheDarkestDay commented on test/generate-entity.test.js
> +const generateEntity = require(`../src/generate-entity`);
Все правильно.

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +    console.log(`See ya next time!`);
Оставляю на твое усмотрение.

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +async function checkAndWrite(fileDir, entities) {
С тестами тут я бы предложил пока забить, потому что совсем неочевидно, как это тестировать - в идеале нужно  придумать модуль-заглушку для `fs`, чтобы в ходе тестов не работать с настоящей файловой системой. Это можно сделать достаточно просто с помощью сторонних библиотек для моков, но мы вроде как избегаем на интенсиве их использования, дабы следовать программе. 

Можно, конечно, сделать это все самому, но тогда нужно будет реализовать внедрение зависимостей для модуля с командой генерации - во время нормального выполнения в него инжектировался бы "нормальный" модуль fs, а во время тестов - заглушка, повторяющая по интерфейсу модуль `fs`. Но такая реализация прибавляет сложности и без того непростому заданию

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +  async execute() {
Я бы просто назвал этот модуль `main`, тем самым указав, что это - основной модуль приложения и как бы точка входа.

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +const entityDefaultConfig = require(`../config`).entity;
Можно воспользоваться деструктуризацией здесь.

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +    process.exit(1);
Как вариант, вот так: https://pastebin.com/CNJ4Y5UE

2018-10-10 04:14 UTC, TheDarkestDay commented on src/commands/greet.js
> +    shouldWrite = true;
В случае возникновения ошибки я бы скорее хотел прервать выполнение программы и вывести соответствующее сообщение, нежели пытаться дальше записывать файл. Тогда можно было бы внутри это функции вообще избавиться от `try/catch`, а все обрабатывать только в самой верхней функции - `execute`.

Или же можно оставить `try/catch` здесь, если ты хочешь индивидуально обрабатывать разные ошибки (например, выводить разные сообщения на ошибки от `access` или `writeFile`). но тогда нужно будет в блоке `catch` эту ошибку пробросить, чтобы обработчик ошибки в функции `execute` тоже мог её поймать и отобразить.

2018-10-10 04:17 UTC, RayProud commented on src/commands/greet.js
> +    shouldWrite = true;
Видимо, тут не совсем очевидный код получился.

На самом деле, тут обрабывается не ошибка работы кода, а ошибка доступа к файлу. Иначе говоря, если `access` выкинул ошибку, то значит, что такого файла нет и можно по такому пути сохранять данные. 

Как думаешь, как сделать явнее?

2018-10-10 04:30 UTC, TheDarkestDay commented on src/commands/greet.js
> +    shouldWrite = true;
Тут есть проблема: `fs.access` бросит ошибку не только в случае, если файла нет. Например, отсутствие прав на работу с файлом тоже приведет к ошибке, и твое приложение ошибочно решит, что запись по пути можно осуществить. 

В [документации](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) есть примеры таких проверок с помощью метода `fs.open`. Думаю, стоит просто вынести эту процедуру в отдельную функцию и там отслеживать конкретный код ошибки - если `ENOENT`, тогда действительно файла нет и можно начать запись, иначе - возникла какая-то другая ошибка и нужно аварийно завершить выполнение.

2018-10-10 17:20 UTC, RayProud commented on src/commands/greet.js
> +    process.exit(1);
Круто. Сделал.

2018-10-10 17:21 UTC, RayProud commented on src/commands/greet.js
> +  async execute() {
Сделал.

2018-10-10 17:21 UTC, RayProud commented on src/commands/greet.js
> +const entityDefaultConfig = require(`../config`).entity;
Сделал.

2018-10-10 17:30 UTC, RayProud commented on src/commands/main.js
> +  return new Promise((resolve) => rl.question(question, (answer) => resolve(answer)));
Хотел вынести в `helpers/common`, но понял, что либо нужно будет в хелпере создавать каждый раз интерфейс readline (что мне не очень нравится), либо прокидывать интерфейс аргументом, что почему-то тоже кажется сомнительным.

Норм тут оставить?

2018-10-10 17:30 UTC, RayProud commented on src/commands/main.js
> +          return writeFile(fileDir, JSON.stringify(entities));
С одной стороны кажется, что странно мешать синтаксис async/await и promise,  но зато так нет try/catch внутри try/catch, а иначе не поймать ошибку `EEXIST `.

Как в отдельную функцию это вынести не придумал. А использовать `access` для записи не рекомендуют, потому что может быть рассинхрон в момент записи (то есть, проверили, вроде ок, в callback'е начинаем писать, а файл уже изменился).

2018-10-10 17:30 UTC, RayProud commented on src/commands/main.js
> +          return null;
Мне тут нужно выйти из ошибки. Не придумал, как иначе выйти.

2018-10-10 17:30 UTC, RayProud commented on src/commands/main.js
> +      process.exit(1);
Так как это ошибка не по сценарию, то сообщаем о ней и аварийно выходим.

2018-10-11 03:39 UTC, TheDarkestDay requested changes

2018-10-11 03:39 UTC, TheDarkestDay commented on src/commands/main.js
> +  return new Promise((resolve) => rl.question(question, (answer) => resolve(answer)));
Норм.

2018-10-11 03:39 UTC, TheDarkestDay commented on src/commands/main.js
> +    .catch((err) => {
Разве этот `catch` нужен? Ошибку предыдущего `catch` спокойно поймает обработчик самого верхнего уровня - тот, что в функции `execute`.

2018-10-11 03:39 UTC, TheDarkestDay commented on src/commands/main.js
> +          return writeFile(fileDir, JSON.stringify(entities));
Функции `checkAndWrite` в таком случае вовсе не нужно быть асинхронной (я имею в виду, ей не нужно ключевое слово `async` в объявлении). Тогда её можно сделать обычной функцией возвращающей промис от вызова `writeFile`.

2018-10-11 03:39 UTC, TheDarkestDay commented on src/commands/main.js
> +      process.exit(1);
Остальные вызовы асинхронных функций тоже необходимо занести в блок `try/catch`, иначе существует риск не обработать ошибки от `rl.question`, например.

2018-10-11 03:52 UTC, RayProud commented on src/commands/main.js
> +    .catch((err) => {
Не нужен. Убрал.

2018-10-11 03:55 UTC, RayProud commented on src/commands/main.js
> +          return writeFile(fileDir, JSON.stringify(entities));
Согласен.

2018-10-11 03:56 UTC, RayProud commented on src/commands/main.js
> +      process.exit(1);
Согласен.
Внёс.

2018-10-11 04:09 UTC, merged