server for static files
htmlacademy-nodejs/22908-keksobooking pull request #9
Opened 2018-10-13 12:54 UTC by RayProud

2018-10-13 13:01 UTC, RayProud commented on src/commands/server.js
> +  const extsMap = {
С одной стороны, это хелперы какие-то, а с другой, другого сервера нет. Они используются только здесь,

Разве что можно вынести getContentTypePath, resolveFileAddress и readFile в `src/helpers/server`, но я не понял, если ли от этого толк.

2018-10-13 13:01 UTC, RayProud commented on src/commands/server.js
> +  const ext = extname(path).slice(1);
Решил, что лучше в одном месте убирать точку, чем каждый раз добавлять её в ключи мапы.

2018-10-13 13:01 UTC, RayProud commented on src/commands/server.js
> +      break;
Вроде других исключений нет, кроме `index.html`. Но может понадобиться для serviceWorker, например.

2018-10-13 13:01 UTC, RayProud commented on src/commands/server.js
> +      'content-type': `text/plain`,
Здесь обратные кавычки поставить нельзя.

`SyntaxError: Unexpected template string`

2018-10-13 13:01 UTC, RayProud commented on src/commands/server.js
> +      await readFile(fileAddress, res);
Тут думаю, может, если эта функция не только читает, но и закрывает запрос, может нужно переименовать в `sendFile`?

2018-10-13 13:01 UTC, RayProud commented on src/commands/server.js
> +      console.warn(colors.yellow(`'port' argument should be a number. The server will try listen on 3000.`));
Думаю, что падать приложение не должно, если ерунду передали, но сказать про это нужно.

2018-10-14 06:44 UTC, TheDarkestDay requested changes

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +  const extsMap = {
Пусть будут здесь.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +  const ext = extname(path).slice(1);
Хорошо.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +      break;
Хорошо.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +  return join(address);
`join` используется для соединения нескольких строковых аргументов в один путь, соответствующий формату текущей файловой системы. В твоем же случае, аргумент только один и если я все верно понял, `join` нужен только для нормализации пути и вставки правильных разделителей. Для достижения именно этой цели в модуле `path` есть функция `normalize`.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +      await readFile(fileAddress, res);
Да, согласен.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +      'content-type': `text/plain`,
Потому что шаблонные строки, как правило, возвращают какое-то вычисляемое содержимое -  а значит, для использования их в качестве ключей объекта необходимо воспользоваться синтаксисом computed properties - то есть, обернуть ключ объекта в квадратные скобки.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +      console.warn(colors.yellow(`'port' argument should be a number. The server will try listen on 3000.`));
Хорошо.

2018-10-14 06:44 UTC, TheDarkestDay commented on src/commands/server.js
> +  (async () => {
Есть ли какая-то причина, чтобы оборачивать в асинхронную функцию конкретный участок кода, вместо того, чтобы всю функцию-обработчик сделать асинхронной? Тогда можно будет всю логику обернуть в один блок `try/catch`, где в `catch` мы проверяли бы код ошибки - если `ENOENT`, значит возвращаем 404, иначе что-то пошло не так и возвращаем 500.

2018-10-14 08:09 UTC, RayProud commented on src/commands/server.js
> +  (async () => {
Причин нет. Переписал.

2018-10-14 08:09 UTC, RayProud commented on src/commands/server.js
> +  return join(address);
Согласен.
Поправил.

2018-10-14 08:09 UTC, RayProud commented on src/commands/server.js
> +      await readFile(fileAddress, res);
Поменял.

2018-10-14 08:09 UTC, RayProud commented on src/commands/server.js
> +      'content-type': `text/plain`,
Точно. Сделал.

2018-10-14 09:28 UTC, TheDarkestDay requested changes

2018-10-14 09:28 UTC, TheDarkestDay commented on src/commands/server.js
> +    res.writeHead(500, err.message, {
В случае ошибки `ENOENT` мы здесь пытаемся записать данные в уже закрытый поток. К нашему счастью, это работает, но тем не менее, выглядит как избыточная операция.

2018-10-14 09:30 UTC, RayProud commented on src/commands/server.js
> +    res.writeHead(500, err.message, {
Хм. Забыл return.

2018-10-14 09:31 UTC, RayProud commented on src/commands/server.js
> +    res.writeHead(500, err.message, {
Поправил

2018-10-14 09:33 UTC, TheDarkestDay approved these changes

2018-10-14 09:33 UTC, merged